# Template sections: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy.html
Transform: AWS::Serverless-2016-10-31

Resources:
  # https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md#httpapi
  ApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
        AllowOrigins:
          - "*"

  # https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.12
      Handler: app.main.lambda_handler
      CodeUri: ./
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          LOGGING_LEVEL: !Sub "{{resolve:ssm:/api-python/logging-level}}"
          POSTGRES_URI: !Sub "{{resolve:secretsmanager:postgres-uri:SecretString}}"
          NEO4J_URI: !Sub "{{resolve:secretsmanager:neo4j-uri:SecretString}}"
          NEO4J_PASSWORD: !Sub "{{resolve:secretsmanager:neo4j-password:SecretString}}"
          STRIPE_PUBLIC_KEY: !Sub "{{resolve:ssm:/api-python/stripe-public-key}}"
          STRIPE_SECRET_KEY: !Sub "{{resolve:secretsmanager:stripe-secret-key:SecretString}}"
          STRIPE_WEBHOOK_SECRET: !Sub "{{resolve:secretsmanager:stripe-webhook-secret:SecretString}}"
          FIREBASE_PROJECT_ID: !Sub "{{resolve:ssm:/api-python/firebase-project-id}}"
      Events:
        RootRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref ApiGateway
            Path: /
            Method: ANY
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiEndpoint:
    Description: HTTP API Gateway endpoint URL
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com
