services:
  api-python:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - ${HOST_API_PORT}:8000
    command: sleep infinity
    depends_on:
      - postgres
      - neo4j
    volumes:
      - ..:/api-python:cached
    environment:
      TZ: ${TZ} # Timezone
      GITHUB_TOKEN: ${GITHUB_TOKEN} # Github CLI
      LOGGING_LEVEL: DEBUG # Python logging
      HOST_API_PORT: ${HOST_API_PORT}
      POSTGRES_URI: postgresql://postgres:developer@postgres:5432/postgres
      NEO4J_URI: neo4j://neo4j:7687
      NEO4J_PASSWORD: developer

  postgres:
    image: postgres
    ports:
      - ${HOST_POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: developer

  neo4j:
    image: neo4j
    ports:
      - ${HOST_NEO4J_PORT}:7687
      - ${HOST_NEO4J_BROWSER_PORT}:7474
    volumes:
      - neo4j_data:/data
    environment:
      NEO4J_AUTH: neo4j/developer

volumes:
  postgres_data:
  neo4j_data:
