version: "3.8"
services:
  api-python:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    depends_on:
      - postgres
    volumes:
      - ..:/api-python:cached
    environment:
      TZ: ${TZ} # Timezone
      GITHUB_TOKEN: ${GITHUB_TOKEN} # Github CLI
      LOGGING_LEVEL: "DEBUG" # Python logging
      POSTGRES_URI: postgresql://developer:developer@postgres:5432/developer

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: developer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
