services:
  api-python:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - ${HOST_API_DEV_PORT}:8000
      - ${HOST_API_DOCKER_PORT}:8001
      - ${HOST_API_SAM_PORT}:8002
      - ${HOST_FIREBASE_AUTH_EMULATOR_PORT}:9099
      - ${HOST_FIREBASE_EMULATOR_UI_PORT}:9090
    command: sleep infinity
    depends_on:
      - postgres
      - neo4j
    volumes:
      - ..:/api-python:cached
    environment:
      TZ: ${TIME_ZONE}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      # Python
      LOGGING_LEVEL: DEBUG
      # Postgres
      POSTGRES_URI: postgresql://postgres:developer@postgres:5432/postgres
      # Neo4j
      NEO4J_URI: neo4j://neo4j:7687
      NEO4J_PASSWORD: developer
      # Stripe (test mode)
      STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      # Firebase
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_AUTH_EMULATOR_HOST: localhost:9099

  postgres:
    image: postgres
    ports:
      - ${HOST_POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: developer

  neo4j:
    image: neo4j
    ports:
      - ${HOST_NEO4J_PORT}:7687
      - ${HOST_NEO4J_BROWSER_PORT}:7474
    volumes:
      - neo4j_data:/data
    environment:
      NEO4J_AUTH: neo4j/developer

volumes:
  postgres_data:
  neo4j_data:
