name: Test
on:
  pull_request:
    branches:
      - main
    paths:
      - "pytest.ini"
      - ".pytest.ini"
      - "pyproject.toml"
      - "pyproject.lock"
      - "tests/**"
      - "*.py"
      - "app/**"
      - ".github/workflows/test.yml"
jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: |
          pip install poetry
          poetry install --no-interaction
      - name: Run tests
        run: poetry run pytest
